import { GetServerSideProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import { parseCookies } from 'nookies';
import { FormEvent, useContext, useState } from 'react'
import styles from '../../styles/Home.module.scss'
import { AuthContext } from '../contexts/AuthContext';

export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const { signIn, isAuthenticated } = useContext(AuthContext);

  async function handleSubmit (event: FormEvent) {
    event.preventDefault();

    await signIn({ email, password });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Authentication and Authorization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form className={styles.form} onSubmit={handleSubmit}>
          <div className={styles.formControl}>
            <input type="email" name="email" id="email" value={email} onChange={({ target }) => setEmail(target.value)} />
          </div>
          <div className={styles.formControl}>
            <input type="password" name="password" id="password" value={password} onChange={({ target }) => setPassword(target.value)} />
          </div>
          <button type="submit">Log In</button>
        </form>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = parseCookies(ctx);

  if (cookies['nextauth.token']) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      }
    }
  }

  return {
    props: {}
  }
};